/**
 * Default exercise library seeded on first launch.
 * Dynamic localized labels are injected via entity_translations.
 */
export const DEFAULT_EXERCISES = [
  // Chest
  {
    id: "ex-01",
    name: "Bench Press",
    muscleGroup: "Chest",
    isCustom: false,
    labelPt: "Supino Reto",
    labelEn: "Bench Press",
  },
  {
    id: "ex-02",
    name: "Incline Bench Press",
    muscleGroup: "Chest",
    isCustom: false,
    labelPt: "Supino Inclinado",
    labelEn: "Incline Bench Press",
  },
  {
    id: "ex-03",
    name: "Dumbbell Fly",
    muscleGroup: "Chest",
    isCustom: false,
    labelPt: "Crucifixo",
    labelEn: "Dumbbell Fly",
  },
  {
    id: "ex-04",
    name: "Push-Up",
    muscleGroup: "Chest",
    isCustom: false,
    labelPt: "Flexao",
    labelEn: "Push-Up",
  },

  // Back
  {
    id: "ex-05",
    name: "Deadlift",
    muscleGroup: "Back",
    isCustom: false,
    labelPt: "Terra",
    labelEn: "Deadlift",
  },
  {
    id: "ex-06",
    name: "Pull-Up",
    muscleGroup: "Back",
    isCustom: false,
    labelPt: "Barra Fixa",
    labelEn: "Pull-Up",
  },
  {
    id: "ex-07",
    name: "Barbell Row",
    muscleGroup: "Back",
    isCustom: false,
    labelPt: "Remada Curvada",
    labelEn: "Barbell Row",
  },
  {
    id: "ex-08",
    name: "Lat Pulldown",
    muscleGroup: "Back",
    isCustom: false,
    labelPt: "Puxada Frontal",
    labelEn: "Lat Pulldown",
  },
  {
    id: "ex-09",
    name: "Seated Cable Row",
    muscleGroup: "Back",
    isCustom: false,
    labelPt: "Remada Sentada",
    labelEn: "Seated Cable Row",
  },

  // Legs
  {
    id: "ex-10",
    name: "Squat",
    muscleGroup: "Legs",
    isCustom: false,
    labelPt: "Agachamento",
    labelEn: "Squat",
  },
  {
    id: "ex-11",
    name: "Leg Press",
    muscleGroup: "Legs",
    isCustom: false,
    labelPt: "Leg Press",
    labelEn: "Leg Press",
  },
  {
    id: "ex-12",
    name: "Romanian Deadlift",
    muscleGroup: "Legs",
    isCustom: false,
    labelPt: "Terra Romeno",
    labelEn: "Romanian Deadlift",
  },
  {
    id: "ex-13",
    name: "Leg Curl",
    muscleGroup: "Legs",
    isCustom: false,
    labelPt: "Flexora",
    labelEn: "Leg Curl",
  },
  {
    id: "ex-14",
    name: "Leg Extension",
    muscleGroup: "Legs",
    isCustom: false,
    labelPt: "Extensora",
    labelEn: "Leg Extension",
  },
  {
    id: "ex-15",
    name: "Calf Raise",
    muscleGroup: "Legs",
    isCustom: false,
    labelPt: "Panturrilha",
    labelEn: "Calf Raise",
  },

  // Shoulders
  {
    id: "ex-16",
    name: "Overhead Press",
    muscleGroup: "Shoulders",
    isCustom: false,
    labelPt: "Desenvolvimento",
    labelEn: "Overhead Press",
  },
  {
    id: "ex-17",
    name: "Lateral Raise",
    muscleGroup: "Shoulders",
    isCustom: false,
    labelPt: "Elevacao Lateral",
    labelEn: "Lateral Raise",
  },
  {
    id: "ex-18",
    name: "Front Raise",
    muscleGroup: "Shoulders",
    isCustom: false,
    labelPt: "Elevacao Frontal",
    labelEn: "Front Raise",
  },
  {
    id: "ex-19",
    name: "Face Pull",
    muscleGroup: "Shoulders",
    isCustom: false,
    labelPt: "Face Pull",
    labelEn: "Face Pull",
  },

  // Arms
  {
    id: "ex-20",
    name: "Barbell Curl",
    muscleGroup: "Arms",
    isCustom: false,
    labelPt: "Rosca Direta",
    labelEn: "Barbell Curl",
  },
  {
    id: "ex-21",
    name: "Hammer Curl",
    muscleGroup: "Arms",
    isCustom: false,
    labelPt: "Rosca Martelo",
    labelEn: "Hammer Curl",
  },
  {
    id: "ex-22",
    name: "Tricep Dip",
    muscleGroup: "Arms",
    isCustom: false,
    labelPt: "Mergulho Triceps",
    labelEn: "Tricep Dip",
  },
  {
    id: "ex-23",
    name: "Tricep Pushdown",
    muscleGroup: "Arms",
    isCustom: false,
    labelPt: "Puxada Triceps",
    labelEn: "Tricep Pushdown",
  },
  {
    id: "ex-24",
    name: "Skull Crusher",
    muscleGroup: "Arms",
    isCustom: false,
    labelPt: "Triceps Testa",
    labelEn: "Skull Crusher",
  },

  // Core
  {
    id: "ex-25",
    name: "Plank",
    muscleGroup: "Core",
    isCustom: false,
    labelPt: "Prancha",
    labelEn: "Plank",
  },
  {
    id: "ex-26",
    name: "Crunch",
    muscleGroup: "Core",
    isCustom: false,
    labelPt: "Abdominal",
    labelEn: "Crunch",
  },
  {
    id: "ex-27",
    name: "Cable Crunch",
    muscleGroup: "Core",
    isCustom: false,
    labelPt: "Abdominal Polia",
    labelEn: "Cable Crunch",
  },
  {
    id: "ex-28",
    name: "Hanging Leg Raise",
    muscleGroup: "Core",
    isCustom: false,
    labelPt: "Elevacao de Pernas",
    labelEn: "Hanging Leg Raise",
  },

  // Full Body
  {
    id: "ex-29",
    name: "Clean and Press",
    muscleGroup: "Full Body",
    isCustom: false,
    labelPt: "Levantamento e Desenvolvimento",
    labelEn: "Clean and Press",
  },
  {
    id: "ex-30",
    name: "Kettlebell Swing",
    muscleGroup: "Full Body",
    isCustom: false,
    labelPt: "Swing com Kettlebell",
    labelEn: "Kettlebell Swing",
  },
  {
    id: "ex-31",
    name: "Burpee",
    muscleGroup: "Full Body",
    isCustom: false,
    labelPt: "Burpee",
    labelEn: "Burpee",
  },
  {
    id: "ex-32",
    name: "Thruster",
    muscleGroup: "Full Body",
    isCustom: false,
    labelPt: "Thruster",
    labelEn: "Thruster",
  },
] as const;
